version: "3.8"

services:
  builder:
    image: itcreator/argentum-toolkit-rust-dev
    build: .
    working_dir: /code
    volumes:
      - ../../..:/code
      - ../../../var/cargo/common:/usr/local/cargo/registry
