services:
  builder:
    image: itcreator/argentum-toolkit-rs-dev
    build:
      context: ../../..
      dockerfile: devops/docker/builder/Dockerfile
    working_dir: /code
    volumes:
      - ../../..:/code
      - ../../../var/cargo/common:/usr/local/cargo/registry
