= Rusty Argentum

== Packages documentation

* link:argentum_event/business/readme.adoc[Argentum Event Business package]
* link:argentum_user/business/readme.adoc[Argentum User Business package]
* link:argentum_user_account/business/readme.adoc[Argentum User Account Business package]
* link:argentum_user_account/infrastructure/readme.adoc[Argentum User Account Infrastructure package]

=== How to setup project

* clone repository
* `devops/scripts/setup.sh`

=== Why "Argentum"?


=== Project structure
Rusty Argentum project is composed of components.
Each component is split to two crates:
business crate for abstractions and infrastructure crate for details of implementation.

What is abstractions? Abstractions are clean business model.
It is the main core of project which responsible for only business logic.
Business package should not depend on 3-rd party packages it is possible.
To follow this restriction you should use Dependency Inversion Principle.

What is details? Details are: database adapters, RESTful API, RPC API
and other connections with world.

[plantuml, format="svg"]
----
rectangle "Rusty Argentum" {
    component Encryption as e {
        package "Encryption Business" as abstractions
        package "Encryption Infrastructure" as details

        details --> abstractions
    }
}
----


WARNING: Business packages should be independent
or should depend only on another business components.

NOTE: Infrastructure packages can depend on business packages, on infrastructure packages
or on 3-rd party packages.

WARNING: Circular dependencies is forbidden.

== Contribution Guideline

=== How to check code

.Code style, tests
[source,bash]
....
$ devops/scripts/check.sh
....

.Check only one package
[source,bash]
....
$ devops/scripts/check-item.sh {{package-name}}
....


=== Allowed 3-rd party packages for business packages of Rusty Argentum

* *thiserror* - errors
* *chrono* - time


== OpenAPI

Pull new version of generator image
[source, bash]
....
$ docker pull openapitools/openapi-generator-cli
....

How to generate a server library
[source, bash]
....
$ docker run --rm -v "${PWD}:/local" -u $(id -u ${USER}):$(id -g ${USER}) openapitools/openapi-generator-cli generate \
    -i /local/argentum_user_account/api-doc/openapi.yaml \
    -g rust-server \
    -o /local/argentum_user_account/api \
    -c /local/argentum_user_account/api-doc/openapi.config.json

$ cargo fmt --manifest-path argentum_user_account/api/Cargo.toml
....

== TODO

* improve error HTTP responses
* add examples to OpenAPI doc
* validation

* documentation, license
* build scripts (behaviour tests, push artifacts)
* https://crates.io/crates/cargo-release
* pre-commit (clippy, rustfmt + autofix)
* improve errors processing
* notifications
