:toc: macro
:toclevels: 3

= Argentum ToolKit

toc::[]

== Why "Argentum"?
Argentum ToolKit was made to provide the easiest way to implement microservices and back-end applications on Rust programming language.
Our goal is to allow everyone to create applications without deep knowledge of Rust.
Of course knowledge of the Rust will be great advantage. But Argentum ToolKit helps you make your first steps as easy as possible and will save much time in the future.
Your learning process will be iterative and easier than without Argentum ToolKit.

.Steps to be ready to create effective applications with Argentum ToolKit
[plantuml, format="svg"]
----
:Run Argentum Demo Application;
:Read Basic Rust Documentation;
:Create Your new Argentum component or application;
:Read more Rust Documentation;
:Now you can quickly create RESTful applications with Argentum;

----

[TIP]
====
**Getting Started with Argentum ToolKit**.

You can try Argentum ToolKit with Docker without deep diving into Rust or the architecture of Argentum ToolKit.

It is easy with link:docs/quick-start.adoc[Quick Start Guide]
====

== Components documentation

* link:argentum_encryption/readme.adoc[Argentum Encryption]
* link:argentum_event/readme.adoc[Argentum Event]
* link:argentum_log/readme.adoc[Argentum Log]
* link:argentum_notification/readme.adoc[Argentum Notification]
* link:argentum_standard/readme.adoc[Argentum Standard]
* link:argentum_user/readme.adoc[Argentum User]
* link:argentum_user_account/readme.adoc[Argentum User Account]


== Argentum ToolKit Architecture. Short description
Argentum ToolKit project is composed of components.
Each component is usually split to several crates:

- business crate for abstractions
- infrastructure crate for details of implementation.
- OpenAPI documentation (Swagger)
- Generated API package

What is **abstractions**? Abstractions are a clean business model.
It is the main core of the project which responsible for only business logic.
A Business package should not depend on 3-rd party packages it is possible.
To follow this restriction you should use Dependency Inversion Principle.

What is **details**? Details are: database adapters, RESTful API, RPC API
and other connections with world.

NOTE: Of course, you are free to follow other project structures.
However, we advise you to pay maximum attention to the business logic of your application
and separate it from the infrastructure.

.The main idea of the architecture of Argentum ToolKit
[plantuml, format="svg"]
----
rectangle "Argentum ToolKit" {
    component Encryption as e {
        package "Encryption Business" as abstractions
        package "Encryption Infrastructure" as details

        details --> abstractions
    }
}
----


WARNING: Package with business logic should be independent
or should depend only on other business packages.

NOTE: Infrastructure packages can depend on business packages,
on other infrastructure packages
or on 3-rd party packages.

WARNING: Circular dependencies are forbidden.

== Features

- Independent components
- Dependency Injection

== Contributing Guideline

If you want to contribute to Argentum ToolKit you just need to follow couple easy rules:

- Be sure that you code follow code standards
- Your code with business logic doesn't depend on infrastructure code and 3-rd party code

=== How to create new component

We prepared the guide how to link:docs/create-component.adoc[create new component].

=== How to check code

.Code style, tests
[source,bash]
....
$ devops/scripts/check.sh
....

.Check only one package
[source,bash]
....
$ devops/scripts/check-item.sh {{package-name}}
....


=== Allowed 3-rd party packages for business packages of Argentum ToolKit

* *thiserror* - errors
* *chrono* - time


== TODO

* openapi merge tool
** error handling
* rest-generator
** generate `path params`
** fix code duplication
** adoc documentation for `argentum_rest`
** generate readme.adoc
** ?Use Generated response for Error responses instead of `Err(HttpError::Conflict(Conflict::new(Box::new(e))))`?
** publish generator to hub.docker.com
** tests

* New type for Password
* add examples to OpenAPI doc
* parsing instead of validation

* DB
** update diesel-ulid 0.2.x up to latest

* documentation
** ADR
** codegen
** other?
* Custom API generator
* OpenTelemetry
* build scripts (behaviour tests, push artifacts)
* run docker images as a local user
* https://crates.io/crates/cargo-release
* notifications
* macro for creation Id types (for user, for account for event)
