:toc: macro
:toclevels: 3

= Rusty Argentum

toc::[]

== Packages documentation

* link:argentum_event/business/readme.adoc[Argentum Event Business package]
* link:argentum_user/business/readme.adoc[Argentum User Business package]
* link:argentum_user_account/business/readme.adoc[Argentum User Account Business package]
* link:argentum_user_account/infrastructure/readme.adoc[Argentum User Account Infrastructure package]

=== How to setup project

* clone repository
* `devops/scripts/setup.sh`


=== How to start

Database:
[bash]
----
docker-compose up service.user.db
docker-compose up service.user_account.db
cd argentum_user_account/infrastructure
diesel migration run
----

Demo web application:

[bash]
----
cd demo-webapp
cargo run
----


=== Why "Argentum"?


=== Project structure
Rusty Argentum project is composed of components.
Each component is split to two crates:
business crate for abstractions and infrastructure crate for details of implementation.

What is abstractions? Abstractions are clean business model.
It is the main core of project which responsible for only business logic.
Business package should not depend on 3-rd party packages it is possible.
To follow this restriction you should use Dependency Inversion Principle.

What is details? Details are: database adapters, RESTful API, RPC API
and other connections with world.

[plantuml, format="svg"]
----
rectangle "Rusty Argentum" {
    component Encryption as e {
        package "Encryption Business" as abstractions
        package "Encryption Infrastructure" as details

        details --> abstractions
    }
}
----


WARNING: Business packages should be independent
or should depend only on another business components.

NOTE: Infrastructure packages can depend on business packages, on infrastructure packages
or on 3-rd party packages.

WARNING: Circular dependencies is forbidden.

== Contribution Guideline

=== How to check code

.Code style, tests
[source,bash]
....
$ devops/scripts/check.sh
....

.Check only one package
[source,bash]
....
$ devops/scripts/check-item.sh {{package-name}}
....


=== Allowed 3-rd party packages for business packages of Rusty Argentum

* *thiserror* - errors
* *chrono* - time


== OpenAPI

Pull new version of generator image
[source, bash]
....
$ docker pull openapitools/openapi-generator-cli
....

How to generate a server library
[source, bash]
....
$ docker run --rm -v "${PWD}:/local" -u $(id -u ${USER}):$(id -g ${USER}) openapitools/openapi-generator-cli generate \
    -i /local/argentum_user_account/api-doc/openapi.yaml \
    -g rust-server \
    -o /local/argentum_user_account/api \
    -c /local/argentum_user_account/api-doc/openapi.config.json

$ cargo fmt --manifest-path argentum_user_account/api/Cargo.toml
....

== How to create new package

=== Init package

* Create a package folder
* Add check item to file `link:devops/scripts/check.sh[devops/scripts/check.sh]`
* Create cargo package
** `cargo init`
** configure `Cargo.toml` parameters
* create `readme.adoc` file

=== Add Diesel ORM support if required

WARNING:    You should do it nly for infrastructure packages if it is required.
            Business packages must not be dependent on 3rd party code.

NOTE:   Diesel ORM manual https://diesel.rs/guides/getting-started

* Configure environment
** Add new variable to `.env` `POSTGRES_DB_FOR_{$componentName}`=`$dbName`
** Add new variable with connection string to `.env`. E.g.: `AG_USER_DATABASE_URL=postgres://dev:dev@*:5432/argentum_user`
* Add new BD service to 'docker-compose.yaml' with name `service.{$componentName}.db`
* Add dependencies to `Cargo.toml`
** `diesel = { version = "1.4.4", features = ["postgres", "r2d2", "uuidv07", "chrono"] }`
** `dotenv = "0.15.0"`
** `chrono = { version = "0.4.19", features = ["serde"] }`
** `serde = { version = "1.0", features = ["derive"] }`
** `uuid = { version = "0.8", features = ["serde", "v4"] }`

* Setup diesel
    `DATABASE_URL=postgres://dev:dev@*:54321/argentum_user diesel setup`
* Update diesel.toml
   `file = "src/db_diesel/schema.rs"`
* Create folder `{$componentName}/infrastructure/src/db_diesel`
* Create migrations `DATABASE_URL=postgres://dev:dev@*:54321/argentum_user diesel migration generate create_argentum_user`
* Write the SQL for migrations (`up.sql`)
* `DATABASE_URL=postgres://dev:dev@*:54321/argentum_user diesel migration run`
* Init a connection manager in `di.rs`
    `let user_pg_connection_pool_manager = Arc::new(ConnectionPoolManager::new("AG_USER_DATABASE_URL"));`
* Add it as a dependency to your repositories
* Create file `src/diesel_db/models.rs`


NOTE: NOTE: When you create a new DB for a new component we recommend you make `name of DB `
equal to the name of the component. E.g. for component with name `User` we will create db with name `argentum_user`

== TODO

* improve error HTTP responses
* add examples to OpenAPI doc
* validation

* documentation, license
* build scripts (behaviour tests, push artifacts)
* https://crates.io/crates/cargo-release
* improve errors processing
* notifications
