[package]
name = "argentum_user_ui"
description = "Argentum User component. UI"
version = "0.3.0-dev"
license = "BSD-3-Clause"
edition = "2021"

readme = "readme.adoc"

[dependencies]
argentum_user_rest = { path = "../../argentum_user/rest", version = ">=0.3.0-dev,<0.4.0", features = ["client"] }
dioxus = { version = "0.6.*", features = ["fullstack"]}
dioxus-logger = "0.6.*"
serde = { version = "1.0.*", features = ["derive"] }
