openapi: 3.1.0

info:
  title: User Account component's responses
  version: 0.2.0-dev

paths: { }

components:
  responses:
    EmptyOk:
      description: OK
      content:
        application/json:
          schema:
            $ref: "./type.oas.yaml#/components/schemas/EmptyResponse"

    400:
      description: Bad request
      content:
        "application/problem+json":
          schema:
            $ref: "./type.oas.yaml#/components/schemas/ProblemDetail"

    401:
      description: Unauthorized
      content:
        "application/problem+json":
          schema:
            $ref: "./type.oas.yaml#/components/schemas/ProblemDetail"

    422:
      description: Unprocessable Entity
      content:
        "application/problem+json":
          schema:
            $ref: "./type.oas.yaml#/components/schemas/ProblemDetail"
