openapi: 3.1.0

info:
  title: Standard component's types (schemas)
  version: 0.2.0-dev
paths: { }

components:
  schemas:
    ProblemDetail:
      title: Schema for error response
      description: "RFC 7807 Problem Details for HTTP APIs"
      required:
        - code
        - title
      properties:
        code:
          type: integer
          format: int32
          minimum: 400
          maximum: 599
          example: '401'
          # example: 401 will be parsed as int. It causes an error
          # https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4930c626eb2d70a28db81c0352dcc797
        message:
          type: string
          example: "{\"some\": \"json\"}"

    EmptyResponse:
      title: Empty response

    DateRange:
      type: object
      required:
        - start
        - end
      properties:
        start:
          type: string
          format: date-time
          example: 2022-10-17T09:28:31.220Z
        end:
          type: string
          format: date-time
          example: 2022-11-17T09:28:31.220Z
