[package]
name = "argentum_user_account_ui"
description = "Argentum User Account component. UI"
version = "0.3.0-dev"
license = "LGPL-3.0"
edition = "2021"

readme = "readme.adoc"

[dependencies]
argentum_rest_infrastructure = { path = "../../argentum_rest/infrastructure", version = ">=0.3.0-dev,<0.4.0"}
argentum_standard_infrastructure = { path = "../../argentum_standard/infrastructure", version = ">=0.3.0-dev,<0.4.0" }
argentum_standard_ui = { path = "../../argentum_standard/ui", version = ">=0.3.0-dev,<0.4.0", default-features = false }
argentum_user_rest = { path = "../../argentum_user/rest", version = ">=0.3.0-dev,<0.4.0", features = ["client"] }
argentum_user_account_rest = { path = "../../argentum_user_account/rest", version = ">=0.3.0-dev,<0.4.0", features = ["client", "ui"] }
dioxus = { version = "0.6.*", features = ["fullstack"]}
dioxus-logger = "0.6.*"
serde = { version = "1.0.*", features = ["derive"] }
uuid = { version = "1.*", features = ["serde", "v4", "js"] }
web-sys = { version = "0.3.*", features = [ "Navigator", "Window", "Storage"] }

[features]
default=[]
web=["argentum_standard_ui/web"]
