[package]
name = "argentum_user_business"
description = "Business layer of user component"
version = "0.3.0-dev"
authors = ["Vital Leshchyk <VitalLeshchyk@gmail.com>"]
license = "LGPL-3.0"
edition = "2024"
homepage = "https://gitlab.com/argentum-toolkit/argentum"
repository = "https://gitlab.com/argentum-toolkit/argentum"
documentation = "https://gitlab.com/argentum-toolkit/argentum"
readme = "readme.adoc"

[dependencies]
#argentum_encryption_business = "0.1.0"
argentum_encryption_business = { path = "../../argentum_encryption/business", version = ">=0.3.0-dev,<0.4.0" }
argentum_standard_business = { path = "../../argentum_standard/business", version = ">=0.3.0-dev,<0.4.0" }
chrono = "0.4.*"
thiserror = "2.0.*"
