[package]
name = "argentum_user_infrastructure"
description = "Business layer of user component"
version = "0.3.0-dev"
authors = ["Vital Leshchyk <VitalLeshchyk@gmail.com>"]
license = "LGPL-3.0"
edition = "2024"
homepage = "https://gitlab.com/argentum-toolkit/argentum"
repository = "https://gitlab.com/argentum-toolkit/argentum"
documentation = "https://gitlab.com/argentum-toolkit/argentum"
readme = "readme.adoc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argentum_db_infrastructure = { path = "../../argentum_db/infrastructure", version = ">=0.3.0-dev,<0.4.0" }
argentum_log_business = { path = "../../argentum_log/business", version = ">=0.3.0-dev,<0.4.0" }
argentum_rest_infrastructure = { path = "../../argentum_rest/infrastructure", features = ["server"], version = ">=0.3.0-dev,<0.4.0" }
argentum_standard_business = { path = "../../argentum_standard/business", version = ">=0.3.0-dev,<0.4.0" }
argentum_standard_infrastructure = { path = "../../argentum_standard/infrastructure", version = ">=0.3.0-dev,<0.4.0" }
argentum_user_business = { path = "../../argentum_user/business", version = ">=0.3.0-dev,<0.4.0" }
argentum_user_rest = { path = "../../argentum_user/rest", features = ["server"], version = ">=0.3.0-dev,<0.4.0" }

chrono = { version = "0.4.*", features = ["serde"] }
futures = "0.3.*"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8.*", features = ["runtime-tokio", "tls-native-tls", "postgres", "uuid", "any", "chrono"] }
uuid = { version = "1.*", features = ["serde", "v4"] }
thiserror = "2.0.*"
