version: "3.8"

services:
  cors:
    image: itcreator/argentum-toolkit-cors-dev
    build:
      context: ../../..
      dockerfile: devops/docker/cors/Dockerfile
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
