mod anonymous_registers_web_boilerplate;
mod anonymous_requests_restore_token_web_boilerplate;
mod anonymous_with_token_changes_password_web_boilerplate;
mod user_logins_with_password_web_boilerplate;
mod user_registers_with_password_web_boilerplate;

pub use anonymous_registers_web_boilerplate::create_anonymous_registers_web_boilerplate;
pub use anonymous_requests_restore_token_web_boilerplate::create_anonymous_requests_restore_token_web_boilerplate;
pub use anonymous_with_token_changes_password_web_boilerplate::create_anonymous_with_token_changes_password_web_boilerplate;
pub use user_logins_with_password_web_boilerplate::create_user_logins_with_password_web_boilerplate;
pub use user_registers_with_password_web_boilerplate::create_user_registers_with_password_web_boilerplate;
