openapi: 3.1.0

info:
  title: User Account component's responses
  version: 0.2.0-dev
paths: { }

components:
  responses:
    AnonymousRegisteredSuccessfully:
      description: Created
      "content":
        "application/json":
          "schema":
            "$ref": "type.oas.yaml#/components/schemas/AnonymousRegistrationResult"

    UserRegisteredSuccessfully:
      description: Created
      "content":
        "application/json":
          "schema":
            "$ref": "type.oas.yaml#/components/schemas/RegistrationWithPasswordResult"

    UserLoggedInSuccessfully:
      description: OK
      "content":
        "application/json":
          "schema":
            "$ref": "type.oas.yaml#/components/schemas/LoginResult"
