openapi: 3.0.3

info:
  title: User Account component's types (schemas)
  version: 0.1.0-dev
paths: {}

components:
  schemas:
    RegistrationWithPasswordSchema:
      type: object
      properties:
        email:
          type: string
          format: email
        name:
          $ref: '../../argentum_user/api-doc/types.oas.yaml#/components/schemas/UserName'
        password:
          type: string
          format: password
      required:
        - email
        - name
        - password

    AnonymousRegistrationResult:
      type: object
      properties:
        anonymous_id:
          type: string
          format: uuid
        token:
          type: string
      required:
        - anonymous_id
        - token

    RegistrationWithPasswordResult:
      type: object
      properties:
        id:
          type: string
          format: uuid
      required:
        - id

    LoginResult:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        token:
          type: string
      required:
        - user_id
        - token

    LoginWithPasswordSchema:
      type: object
      properties:
        email:
          type: string
          format: email
          example: test-email@test-email.com
        password:
          type: string
          format: password
          example: secure-password
      required:
        - email
        - password

    RequestRestoreTokenSchema:
      type: object
      properties:
        email:
          type: string
          format: email
          example: test-email@test-email.com
      required:
        - email

    ChangePasswordSchema:
      type: object
      properties:
        token:
          type: string
        password:
          type: string
          format: password
      required:
        - token
        - password
