[package]
name = "demo-fe-app"
version = "0.1.0"
authors = ["Vital Leshchyk <vitalleshchyk@gmail.com>"]
edition = "2021"

[dependencies]
argentum_rest_infrastructure = { path = "../argentum_rest/infrastructure", version = ">=0.3.0-dev,<0.4.0" }
argentum_standard_business = { path = "../argentum_standard/business", version = ">=0.3.0-dev,<0.4.0" }
argentum_standard_infrastructure = { path = "../argentum_standard/infrastructure", version = ">=0.3.0-dev,<0.4.0" }
argentum_user_account_rest = { path = "../argentum_user_account/rest", version = ">=0.3.0-dev,<0.4.0", features = ["client"] }
argentum_user_rest = { path = "../argentum_user/rest", version = ">=0.3.0-dev,<0.4.0", features = ["client"] }
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.*"

dioxus = { version = "0.5", features = ["fullstack", "router"] }

# Debug
dioxus-logger = "0.5.*"
dioxus-sdk = { version = "0.5.*", features = ["storage"] }
manganis = "^0.2"

uuid = { version = "1.5.*", features = ["serde", "v4"] }
log = "0.4.22"

web-sys = { version = "0.3.*", features = ["Navigator", "Window"] }

[features]
default = []
server = ["dioxus/axum"]
web = ["dioxus/web"]
