[package]
name = "demo-fe-app"
version = "0.1.0"
authors = ["Vital Leshchyk <vitalleshchyk@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }

dioxus = { version = "0.5", features = ["fullstack", "router"] }

# Debug
dioxus-logger = "0.5.*"
dioxus-sdk = { version = "0.5.*", features = ["storage"] }

[features]
default = []
server = ["dioxus/axum"]
web = ["dioxus/web"]
