openapi: 3.0.3

info:
  title: Test
  version: 0.1.0-dev
paths: {}

components:
  schemas:
    TestTestTest2:
      properties:
        tst1:
          type: string
          minLength: 1
          maxLength: 255
          example: Winston
        tst2:
          type: string
          minLength: 1
          maxLength: 255
          example: Marko
