openapi: 3.1.0

info:
  title: User component's types (schemas)
  version: 0.3.0

paths: { }

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 20c31ece-c78c-45d6-9ef3-8452e8eea571
        email:
          type: string
          format: email
          example: test-email@test-email.com
        name:
          $ref: '#/components/schemas/UserName'
      required:
        - email
        - name

    UserName:
      type: object
      properties:
        first:
          type: string
          minLength: 1
          maxLength: 255
          example: Winston
          title: "First Name"
          x-ag-ui:
              id: user_first_name
              name: user_first_name
            #TODO: x-ag-type: 

        last:
          type: string
          minLength: 1
          maxLength: 255
          example: Marko
          title: "Last Name"
          x-ag-ui:
              id: user_last_name
              name: user_last_name

        additional:
          type: string
          minLength: 1
          maxLength: 255
          title: "Additional name"
          x-ag-ui:
            id: user_additional_name
            name: user_additional_name
            weight: 100

      required:
        - first
