openapi: 3.1.0

info:
  title: User component's types (schemas)
  version: 0.2.0-dev

paths: { }

components:
  schemas:
    UserName:
      type: object
      properties:
        first:
          type: string
          minLength: 1
          maxLength: 255
          example: Winston
        last:
          type: string
          minLength: 1
          maxLength: 255
          example: Marko
        patronymic:
          type: string
          minLength: 1
          maxLength: 255

      required:
        - first
