services:
  service.user.db:
    image: 'postgres:16.1'
    command: -c jit=off
    environment:
      - POSTGRES_DB=${POSTGRES_DB_FOR_ARGENTUM_USER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #    user: $HOST_UID:$HOST_GID
    volumes:
      - ../../../var/db/user/data:/var/lib/postgresql/data
    tmpfs:
      - /tmp:exec,size=1G
    ports:
      - "54321:5432"
    #TODO: close ports for production mode
