= Create New Component

== Example

You can look at `Argentum User` component.
It can be good example of component which contains:

* clean business logic (`business`)
* API documentation (`api-doc`)
* HTTP Client and Server generated from API documentation (`api`)
* Infrastructure code which interacts with "real world" (`infrastructure`)
** Database migrations (`migrations`)
** HTTP layer built on `Argentum Rest` (`src/rest`)
** Data persistence layer built on `SQLX` (`src/db`)

== Create file structure

TBD

== How to create new package

=== Init package

* Create a package folder
* Add check item to file `link:devops/scripts/check.sh[devops/scripts/check.sh]`
* Create cargo package
** `cargo init`
** configure `Cargo.toml` parameters
* create `readme.adoc` file

//TODO: DESCRIBE HOW TO DEAL WITH DATABASE
=== Add Diesel ORM support if required

WARNING:    You should do it only for infrastructure packages if it is required.
Business packages must not be dependent on 3rd party code.

NOTE:   Diesel ORM manual https://diesel.rs/guides/getting-started

* Configure environment
** Add new variable to `.env` `POSTGRES_DB_FOR_{$componentName}`=`$dbName`
** Add new variable with connection string to `.env`.
E.g.: `AG_USER_DATABASE_URL=postgres://dev:dev@*:5432/argentum_user`
* Add new BD service to 'docker-compose.yaml' with name `service.{$componentName}.db`
* Add dependencies to `Cargo.toml`
** `diesel = { version = "1.4.4", features = ["postgres", "r2d2", "uuidv07", "chrono"] }`
** `dotenv = "0.15.0"`
** `chrono = { version = "0.4.19", features = ["serde"] }`
** `serde = { version = "1.0", features = ["derive"] }`
** `uuid = { version = "1.4", features = ["serde", "v4"] }`

* Setup diesel
`DATABASE_URL=postgres://dev:dev@*:54321/argentum_user diesel setup`
* Update diesel.toml
`file = "src/db_diesel/schema.rs"`
* Create folder `{$componentName}/infrastructure/src/db_diesel`
* Create migrations `DATABASE_URL=postgres://dev:dev@*:54321/argentum_user diesel migration generate create_argentum_user`
* Write the SQL for migrations (`up.sql`)
* `DATABASE_URL=postgres://dev:dev@*:54321/argentum_user diesel migration run`
* Init a connection manager in `di.rs`
`let user_pg_connection_pool_manager = Arc::new(ConnectionPoolManager::new("AG_USER_DATABASE_URL"));`
* Add it as a dependency to your repositories
* Create file `src/diesel_db/models.rs`

NOTE: When you create a new DB for a new component we recommend you make `name of DB`
equal to the name of the component.
E.g. for component with name `User` we will create db with name `argentum_user`

== How we work with OpenAPI

=== Run generator from sources

[source,bash]
....
cargo run -- \
  --input {{path/to/openapi.yaml} \
  --output {{path/to/output/dir}} \
  --package-name {{my_package_name}} \
  [ADDITIONAL-PARAMS]
....

.Example
[source,bash]
....
cargo run -- \
  --input ../../todo-argentum/api-doc/openapi.yaml \
  --output ../../todo-argentum/rest/ \
  --package-name todo_rest
....

=== Run generator on Docker../../todo-on-rust-and-hyper/api-doc/openapi.yaml

=== Deprecated
//TODO: generate with rest generator

Pull new version of OpenAPI generators image

[source,bash]
....
$ docker pull openapitools/openapi-generator-cli:v6.6.0
....

How to generate a library with code clients and servers code

[source,bash]
....
$ docker run --rm \
    -v "${PWD}:/local" \
    -u $(id -u ${USER}):$(id -g ${USER}) \
    openapitools/openapi-generator-cli:v7.6.0 generate \
        -i /local/argentum_user_account/api-doc/openapi.yaml \
        -g rust-server \
        -t /local/openapi-templates/rust-server \
        -o /local/argentum_user_account/api \
        -c /local/argentum_user_account/api-doc/openapi.config.json

$ cargo fmt --manifest-path argentum_user_account/api/Cargo.toml
....

docker run --rm -v "${PWD}:/local" -u $(id -u ${USER}):$(id -g ${USER}) openapitools/openapi-generator-cli:v7.6.0 generate -i /local/argentum_user/api-doc/openapi.yaml -g rust-server -o /local/argentum_user/api -c /local/argentum_user/api-doc/openapi.config.json
