[package]
name = "argentum_rest_infrastructure"
description = "The infrastructure layer of REST component"
version = "0.3.1"
authors = ["Vital Leshchyk <VitalLeshchyk@gmail.com>"]
license = "LGPL-3.0"
edition = "2024"
homepage = "https://gitlab.com/argentum-toolkit/argentum"
repository = "https://gitlab.com/argentum-toolkit/argentum"
documentation = "https://gitlab.com/argentum-toolkit/argentum"
readme = "README.md"

[features]
server = ["dep:tokio"]

[dependencies]
async-trait = "0.1.*"

bytes = "1.5.*"
erased-serde = "0.4.*"
http = "1.*"
http-body-util = "0.1.*"
hyper = { version = "1.*", features = ["full"] }
pin-project-lite = "0.2.*"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.*"
serde_valid = "1.*"
tokio = { version = "^1.40", features = ["full"], optional = true }
thiserror = "2.0.*"


argentum_log_business = { path = "../../argentum_log/business", version = ">=0.3.0,<0.4.0" }
argentum_standard_business = { path = "../../argentum_standard/business", version = ">=0.3.0,<0.4.0" }
argentum_standard_infrastructure = { path = "../../argentum_standard/infrastructure", version = ">=0.3.0,<0.4.0" }
argentum_user_account_business = { path = "../../argentum_user_account/business", version = ">=0.3.0,<0.4.0" }
argentum_user_business = { path = "../../argentum_user/business", version = ">=0.3.0,<0.4.0" }
